# ~/.streamlit/config.toml (copy from repo root: streamlit_config_example.toml)
[server]
headless = true
port = 8501
address = "localhost"        # set to "0.0.0.0" to share on LAN
runOnSave = true
fileWatcherType = "auto"

[client]
showSidebarNavigation = true

[theme]
base = "light"

[runner]
fastReruns = true
magicEnabled = false

[logger]
level = "info"
