name: Coverage Pages (main)
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Run tests (no gate for publish)
        continue-on-error: true
        env:
          COVERAGE_MIN: 0
        run: |
          pytest -q --cov=. --cov-report=xml --cov-report=term-missing
      - name: Generate HTML report
        run: |
          coverage html || true
          if [ ! -d "htmlcov" ]; then
            mkdir -p htmlcov && echo "<h1>No coverage available</h1><p>Tests failed or no data.</p>" > htmlcov/index.html
          fi
      - name: Prepare /main folder
        run: |
          rm -rf out && mkdir -p out/main
          cp -r htmlcov/* out/main/
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          keep_files: true
          commit_message: "docs(coverage): update main coverage HTML"
