name: Docker Smoke Test

on:
  pull_request:
    branches: [ main, master ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: tokintel:test
      - name: Streamlit help check
        run: |
          docker run --rm tokintel:test python -m streamlit --help | head -n 5
