name: Docs Matrix Auto‑Clear
on:
  check_suite:
    types: [completed]

permissions:
  contents: read
  pull-requests: write

jobs:
  autoclear:
    runs-on: ubuntu-latest
    if: >
      github.event.check_suite.conclusion == 'success' &&
      github.event.check_suite.pull_requests[0].number != null
    steps:
      - name: Remove test-matrix label if present
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.check_suite.pull_requests?.[0];
            if (!pr) { core.info('No PR found'); return; }
            const owner = context.repo.owner, repo = context.repo.repo, pull_number = pr.number;
            const {data: labels} = await github.rest.issues.listLabelsOnIssue({owner, repo, issue_number: pull_number});
            const names = labels.map(l => l.name);
            if (names.includes('test-matrix')) {
              await github.rest.issues.removeLabel({owner, repo, issue_number: pull_number, name: 'test-matrix'});
              core.notice(`Removed 'test-matrix' from PR #${pull_number} after green checks.`);
            } else {
              core.info("Label 'test-matrix' not present; nothing to do.");
            }
