name: fast-tests
on: [push, pull_request]
jobs:
  fast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run fast unit tests
        run: |
          make test-fast || python -m pytest -q tests/unit/test_timing_config.py tests/unit/test_stats_csv_export.py
