name: GH Pages Cleanup (PR previews)
on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Remove folders for PRs that are closed/merged
        env:
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eo pipefail
          shopt -s nullglob
          for d in pr-*; do
            PR_NUM="${d#pr-}"
            STATUS=$(curl -s -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github+json" https://api.github.com/repos/${REPO}/pulls/${PR_NUM} | jq -r '.state' || echo "unknown")
            if [ "${STATUS}" != "open" ]; then
              echo "Removing ${d} (state=${STATUS})"
              rm -rf "${d}"
            else
              echo "Keeping ${d} (state=open)"
            fi
          done
      - name: Commit & push if changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(gh-pages): auto-clean closed PR previews"
            git push
          else
            echo "No changes to commit."
