name: Monitor CI/Visual (Hourly, Path‑Filtered + Log + Matrix)

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'Makefile'
      - 'docs/**'
      - 'scripts/**'
      - 'exports/**'
  workflow_dispatch:
    inputs:
      targets:
        description: "Target Makefile (spazio-separati)"
        default: "self-check"
        required: true
      python-version:
        description: "Versione Python (vuoto = matrix 3.10/3.11)"
        default: ""
        required: false
  schedule:
    - cron: "7 * * * *"

permissions:
  contents: write
  actions: read

concurrency:
  group: monitor-ci-visual
  cancel-in-progress: true

jobs:
  gate:
    name: Path change gate (last 90m for schedule)
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.gate.outputs.skip }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - id: gate
        run: |
          echo "skip=false" >> $GITHUB_OUTPUT
          if [ "${{ github.event_name }}" = "schedule" ]; then
            CHANGED=$(
              git log --since="90 minutes ago" --name-only --pretty=format: \
              | grep -E '^(Makefile|docs/|scripts/|exports/)' | wc -l || true
            )
            if [ "$CHANGED" -eq 0 ]; then
              echo "skip=true" >> $GITHUB_OUTPUT
            fi
          fi

  monitor:
    name: Monitor CI/Visual
    needs: gate
    if: needs.gate.outputs.skip == 'false' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        py: [ "3.10", "3.11" ]

    env:
      RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      TARGETS: ${{ github.event.inputs.targets || 'self-check' }}
      # Se l'input python-version è vuoto, usa la matrix; altrimenti forza l'input.
      PY_VERSION_EFFECTIVE: ${{ github.event.inputs.python-version != '' && github.event.inputs.python-version || matrix.py }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python ${{ env.PY_VERSION_EFFECTIVE }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION_EFFECTIVE }}

      - name: Install minimal deps (se presenti)
        run: |
          [ -f requirements.txt ] && pip install -r requirements.txt || true

      - name: Make targets (self-check di default)
        id: run_targets
        run: |
          set -e
          echo "👉 Eseguo target: $TARGETS"
          START_TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          for t in $TARGETS; do
            echo "=== make $t ==="
            make $t
          done
          END_TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          echo "start=${START_TS}" >> $GITHUB_OUTPUT
          echo "end=${END_TS}"   >> $GITHUB_OUTPUT

      - name: Upload artifacts (se esistono)
        uses: actions/upload-artifact@v4
        with:
          name: monitor-ci-visual-${{ github.run_id }}-py${{ env.PY_VERSION_EFFECTIVE }}
          path: |
            exports/last_export.json
            docs/status.json
            logs/
          if-no-files-found: ignore
          retention-days: 7

      - name: Aggiorna status.json + monitor_history.json + README
        if: always()
        run: |
          python - <<'PY'
          import json, os, re, datetime, pathlib
          run_url = os.environ.get("RUN_URL")
          event_name = os.environ.get("GITHUB_EVENT_NAME")
          targets = os.environ.get("TARGETS","self-check")
          start = os.environ.get("steps.run_targets.outputs.start","")
          end   = os.environ.get("steps.run_targets.outputs.end","")
          conclusion = os.environ.get("JOB_STATUS","success")
          now = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
          status_path = pathlib.Path("docs/status.json")
          hist_path   = pathlib.Path("docs/monitor_history.json")
          readme_path = pathlib.Path("README.md")
          status = {"docs_ready":"unknown","updated_at":None,"monitor_last_run":None,"monitor_result":None,"monitor_targets":None,"monitor_run_url":None}
          if status_path.exists():
            try: status = json.loads(status_path.read_text(encoding="utf-8"))
            except: pass
          status["monitor_last_run"]=now
          status["monitor_result"]=conclusion
          status["monitor_targets"]=targets
          status["monitor_run_url"]=run_url
          status_path.write_text(json.dumps(status,indent=2,ensure_ascii=False)+"\n",encoding="utf-8")
          hist={"runs":[]}
          if hist_path.exists():
            try: hist = json.loads(hist_path.read_text(encoding="utf-8"))
            except: pass
          entry={"timestamp":now,"result":conclusion,"targets":targets,"event":event_name,"run_url":run_url,"run_id":os.environ.get("GITHUB_RUN_ID")}
          hist["runs"]=([entry]+hist.get("runs",[]))[:20]
          hist_path.write_text(json.dumps(hist,indent=2,ensure_ascii=False)+"\n",encoding="utf-8")
          def icon(r): return "🟢" if r.lower()=="success" else ("🟡" if r.lower()=="neutral" else "🔴")
          rows=[]
          for r in hist["runs"][:5]:
            ts=r["timestamp"].replace("T"," ").replace("Z"," UTC")
            rows.append(f"| {ts} | {icon(r['result'])} {r['result']} | `{r['targets']}` | [run]({r['run_url']}) |")
          block="\n".join(["","| Timestamp | Esito | Targets | Dettagli |","|---|---|---|---|",*rows,""])
          start_marker="<!-- MONITOR_STATUS:START -->"; end_marker="<!-- MONITOR_STATUS:END -->"
          readme = readme_path.read_text(encoding="utf-8")
          pat=re.compile(re.escape(start_marker)+".*?"+re.escape(end_marker),re.S)
          new=f"{start_marker}\n{block}\n{end_marker}"
          if pat.search(readme): readme=pat.sub(new,readme)
          else: readme += "\n\n"+new+"\n"
          readme_path.write_text(readme,encoding="utf-8")
          PY
        env:
          JOB_STATUS: ${{ job.status }}

      - name: Commit e push aggiornamenti
        if: always()
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/status.json docs/monitor_history.json README.md || true
          if git diff --cached --quiet; then
            echo "ℹ️  Nessuna modifica da committare."
          else
            git commit -m "docs(monitor): aggiorna status, history e README [skip ci]"
            git push
          fi
