name: Perf Nightly

on:
  schedule:
    - cron: "0 2 * * *"   # ogni notte alle 02:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run perf checks
        run: |
          python - << 'PY'
          import time, random
          # TODO: sostituire con suite reale
          print("✅ Perf smoke OK")
          time.sleep(0.2)
          print("latency_ms=", int(50 + random.random()*10))
          PY
