name: PR Checks
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ "main" ]
permissions:
  contents: read
  pull-requests: write
jobs:
  label-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add default labels
        if: github.event.action == 'opened'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "ci"
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          [ -f requirements.txt ] && pip install -r requirements.txt || true
      - name: Tests
        run: |
          [ -d tests ] && pytest -q || echo "No tests dir, skipping"
